### ISSUE TITLE
Version that supports both versions of PHP

### ISSUE THREAD

**Issue by jakublabno** [Roave/BetterReflection#1137] opened 2022-06-24 14:15 UTC
I don't see any version that works on both, 7.4 and 8.0 PHP versions, could you add support?

**Comment by asgrim** [comment] 2022-06-24 14:57
Duplicate of #984 - specifically

> BR 5.1.x running in PHP 8 can analyse all older versions of PHP code, so it doesn't matter what version of PHP the codebase being analysed is, as long as the version of PHP running BR is PHP 8+

**Comment by asgrim** [comment] 2022-06-24 14:58
Hope this helps! Please let us know if you have any further questions :)

**Closed as completed by asgrim** 2022-06-24 14:58 UTC
Labels: duplicate

**Comment by jakublabno** [comment] 2022-06-24 15:04
So it's wrong spec in composer
![image](https://user-images.githubusercontent.com/64330419/175563159-a77702ce-ef35-4520-b999-e9338748d9bb.png)

**Comment by asgrim** [comment] 2022-06-24 15:05
Not quite; you have to run it with PHP 8/8.1, but it can analyse code that runs on older PHP versions, if that makes sense :) for example you could run it in a Docker container to analyse
