### ISSUE TITLE
Result of `BetterReflection\ReflectionParameter::isDefaultValueAvailable()` not similar to `\ReflectionParameter::isDefaultValueAvailable()`

### ISSUE THREAD

**Issue by WinterSilence** [Roave/BetterReflection#791] opened 2021-10-02 22:31 UTC
~~~php
class Demo
{
    public function test($value = null)
    {
    }
    public function isDefaultValueAvailable(): bool
    {
        return (new \ReflectionParameter([$this, 'test'], 0))->isDefaultValueAvailable();
    }
}

$demo = new Demo();
var_dump($demo->isDefaultValueAvailable()); // result: true
~~~
`Roave\BetterReflection\Reflection\ReflectionParameter::isDefaultValueAvailable():`
https://github.com/Roave/BetterReflection/blob/74aaf7e9a446590f5a461203c379d0580c614faa/src/Reflection/ReflectionParameter.php#L278

**Comment by Ocramius** [comment] 2021-10-03 00:09
Could you perhaps clarify the expectations? Can this be written in form of a failing test case perhaps?

**Comment by WinterSilence** [comment] 2021-10-03 00:51
@Ocramius replace `\ReflectionParameter` to `Roave\BetterReflection\Reflection\ReflectionParameter`

**Comment by kukulich** [comment] 2021-10-03 05:24
I plan to solve this (with some other things) after #787 and #772 are merged.

**Comment by kukulich** [comment] 2021-10-03 05:45
Hmm... After a coffee... I'm not able to reproduce this bug.

@WinterSilence Can you please create failing test?

**Comment by WinterSilence** [comment] 2021-10-03 05:58
@kukulich
~~~php
<?php
namespace test;
use Roave\BetterReflection\Reflection\ReflectionParameter as BetterReflectionParameter;
class Demo
{
    public function test($value = null)
    {
    }
    public function ReflectionParameter(): bool
    {
        return (new \ReflectionParameter([$this, 'test'], 0))->isDefaultValueAvailable();
    }
    public function BetterReflectionParameter(): bool
    {
        return BetterReflectionParameter::createFromClassInstanceAndMethod($this, 'test', 'value')->isDefaultValueAvailable();
    }
}

$demo = new Demo();
var_dump($demo->ReflectionParameter(), $demo->BetterReflectionParameter()); // true false
~~~

**Comment by kukulich** [comment] 2021-10-03 06:10
@WinterSilence this is not failing test…

**Comment by WinterSilence** [comment] 2021-10-03 06:12
@kukulich I told something about failing tests? 
> Result of BetterReflection\ReflectionParameter::isDefaultValueAvailable() not similar to \ReflectionParameter::isDefaultValueAvailable()

**Comment by kukulich** [comment] 2021-10-03 06:21
@WinterSilence I’m not able to reproduce any bug. So you have to prepare failing test if you want we fix it. Demo is not failing test.

**Comment by WinterSilence** [comment] 2021-10-03 06:43
@kukulich what's return demo? `true false`?

**Comment by kukulich** [comment] 2021-10-03 06:53
@WinterSilence Please create the failing test.

**Comment by WinterSilence** [comment] 2021-10-03 07:22
@kukulich https://github.com/Roave/BetterReflection/pull/795

**Comment by asgrim** [comment] 2021-10-11 13:27
As per [comment](https://github.com/Roave/BetterReflection/pull/795#issuecomment-940031708): 

> @WinterSilence not sure exactly why your test does not pass on your machine, but as it stands, neither @kukulich nor myself can reproduce any issue using your test case I'm afraid :( if you can manage to make a test that does fail, please do ask for this to be re-opened with a failing test and we can investigate.

**Closed as completed by asgrim** 2021-10-11 13:27 UTC
Labels: bug, invalid, needs more info

**Comment by WinterSilence** [comment] 2021-10-12 11:59
@asgrim method still ignore `null` as default value
~~~
class A {
   function test($value = null) {}
}
BetterReflectionParameter::createFromClassInstanceAndMethod(new A(), 'test', 'value')
    ->isDefaultValueAvailable(); // result false!
~~~

**Comment by asgrim** [comment] 2021-10-12 13:10
@WinterSilence Sorry, but this example still does not return `false`. Are you sure there are no extensions / other things interacting oddly with your setup?

**Comment by WinterSilence** [comment] 2021-10-12 15:26
@asgrim  after update all fine

**Comment by Ocramius** [comment] 2021-10-12 16:36
@WinterSilence what version did you update to? Just trying to pin this bug to a specific milestone.

**Comment by WinterSilence** [comment] 2021-10-12 17:45
@Ocramius update to dev-master
