### ISSUE TITLE
PhpInternalSourceLocator not working with functions

### ISSUE THREAD

**Issue by theofidry** [Roave/BetterReflection#407] opened 2018-02-16 10:16 UTC
`PhpInternalSourceLocator` assumes the identifier is always a class whereas it can also be a function in which case it fails to find a reflector.

I tried to do check how to fix but I have trouble to see how you can instantiate the function reflection/or in it

**Comment by asgrim** [comment] 2018-02-16 13:19
Duplicate of #38

**Closed by asgrim** 2018-02-16 13:19 UTC
Labels: duplicate
