### ISSUE TITLE
Call to a member function getInterfacesHierarchy() on null

### ISSUE THREAD

**Issue by Danack** [Roave/BetterReflection#191] opened 2016-04-03 00:37 UTC
Output error:
```
PHP Fatal error:  Uncaught Error: Call to a member function getInterfacesHierarchy() on null in /home/github/GithubArtaxService/GithubArtaxService/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1004
Stack trace:
#0 [internal function]: BetterReflection\Reflection\ReflectionClass->BetterReflection\Reflection\{closure}(Object(PhpParser\Node\Name))
#1 /home/github/GithubArtaxService/GithubArtaxService/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(1006): array_map(Object(Closure), Array)
#2 /home/github/GithubArtaxService/GithubArtaxService/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(842): BetterReflection\Reflection\ReflectionClass->getCurrentClassImplementedInterfacesIndexedByName()
#3 [internal function]: BetterReflection\Reflection\ReflectionClass->BetterReflection\Reflection\{closure}(Object(BetterReflection\Reflection\ReflectionClass))
#4 /home/github/GithubArtaxService/GithubArtaxService/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(844): array in /home/github/GithubArtaxService/GithubArtaxService/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php on line 100
```

Repro code
```
<?php

use BetterReflection\Reflector\ClassReflector;
use BetterReflection\SourceLocator\Type\SingleFileSourceLocator;

$autoloader = require __DIR__.'/../vendor/autoload.php';

exec('wget --no-check-certificate https://raw.githubusercontent.com/guzzle/guzzle/8e4e5ef9fbcc6ced335f398b32dcf2a0e4a24acb/src/Client.php');

$sourceLocator = new SingleFileSourceLocator("./Client.php");

$reflector = new ClassReflector($sourceLocator);
$reflClass = $reflector->reflect('GuzzleHttp\Client');

$properties = $reflClass->getProperties();
$methods = $reflClass->getMethods();

```

**Comment by asgrim** [comment] 2016-04-05 16:01
Duplicate of #189

**Closed by asgrim** 2016-04-05 16:01 UTC
