### ISSUE TITLE
Wrong behavior of `ReflectionMethod::getPrototype()`

### ISSUE THREAD

**Issue by WinterSilence** [Roave/BetterReflection#927] opened 2021-12-25 11:55 UTC
Demo:
~~~php
interface I
{
    public function foo();
}
abstract class A implements I
{
    abstract public function foo(): array;
}
class B extends A
{
    public function foo(): array
    {
        return [];
    }
}
~~~
Native reflection:
~~~php
$c = new \ReflectionClass(A::class);
$m = $c->getMethod('foo');
var_dump($m->getPrototype()->name); // print: `I`
$c = new \ReflectionClass(B::class);
$m = $c->getMethod('foo');
var_dump($m->getPrototype()->name); // print: `A`
~~~
Better reflection:
~~~php
$c = new \ReflectionClass(A::class);
$m = $c->getMethod('foo');
var_dump($m->getPrototype()->getName()); // print: `I`
$c = new \ReflectionClass(B::class);
$m = $c->getMethod('foo');
var_dump($m->getPrototype()->getName()); // print: `I` ERROR
~~~

https://github.com/Roave/BetterReflection/blob/b02fa4d270b582f1d03490db031c695934970bb6/src/Reflection/ReflectionMethod.php#L125
Error: current class is `getCurrentClass()` and it's not always same to `getImplementingClass()`
https://github.com/Roave/BetterReflection/blob/b02fa4d270b582f1d03490db031c695934970bb6/src/Reflection/ReflectionMethod.php#L128
Error: why does `getPrototype()` at first look for interfaces, not classes?
https://github.com/Roave/BetterReflection/blob/b02fa4d270b582f1d03490db031c695934970bb6/src/Reflection/ReflectionMethod.php#L160
Error: abstract method can be declared in interface, `A::foo()` as in demo

**Comment by Ocramius** [comment] 2021-12-25 11:58
Is this for `4.x` or the current `5.0.x` branch?

**Comment by WinterSilence** [comment] 2021-12-25 12:01
@Ocramius I inserted lines with errors in 5.0

**Comment by Ocramius** [comment] 2021-12-25 17:03
Looking further at this, I must say that I don't understand what the use of [`getPrototype()`](https://www.php.net/manual/en/reflectionmethod.getprototype.php) is :D 

I'd say that for our own purposes, we should drop it from our core reflection API in `6.0.0`, only to be kept in the `/Adapter` code

**Comment by asgrim** [comment] 2021-12-25 17:04
Yeah I vaguely remember implementing this and I couldn't figure out the exact use for it :/ sorry

**Comment by WinterSilence** [comment] 2021-12-25 17:56
@Ocramius @asgrim `getDeclaringClass()` it's latest class in chain of nested classes who override method, `getPrototype()` is last/top interface/class in chain of nested interfaces/abstract classes where defined method i.e. last abstraction in chain who re-declare method.
~~~php
interface I
{
    public function foo();
    public function bar();
}
abstract class A implements I
{
    abstract public function foo();
    abstract public function bar();
}
abstract class A2 extends A
{
    abstract public function bar(): array;
}
class B extends A2
{
    public function foo()
    {
           return 1;
    }
    public function bar(): array
    {
           return [];
    }
}
~~~

`B` is declaring class for `foo()` and `bar()`
`A` is  prototype class for `foo()`
`A2` is  prototype class for `bar()`

Note: "re-declare" != "change":
 ~~~php
abstract class A
{
    abstract public function foo();
}
abstract class A2 extends A
{
    abstract public function foo();
}
class B extends A2
{
    public function foo()
    {
           return 1;
    }
}
~~~
`A2` is  prototype class, `B` is declaring class

if useful to find new methods in class or find method comment to replace `@inheridDoc` for child.

**Comment by WinterSilence** [comment] 2021-12-25 18:13
Also, these methods are needed for compatibility with native ReflectionMethod

**Comment by Ocramius** [comment] 2021-12-25 18:17
They're not necessary: they can be **moved** to the adapter layer :)

**Comment by WinterSilence** [comment] 2021-12-25 18:32
@Ocramius they not necessary for you, but it's necessary for code review/static analyze

**Comment by kukulich** [comment] 2022-09-27 20:38
I'm not able to reproduce it. I think this should be closed. Failing test is needed.

**Comment by Ocramius** [comment] 2022-09-27 20:53
Closing here as per @kukulich's feedback

**Closed as completed by Ocramius** 2022-09-27 20:53 UTC
Labels: bug, invalid

**Comment by WinterSilence** [comment] 2022-09-27 21:06
@Ocramius what's you mean?

**Comment by Ocramius** [comment] 2022-09-27 21:17
Needs a failing automation test case in the test suite of this library, in order to be reconsidered.

**Comment by WinterSilence** [comment] 2022-09-27 22:18
@Ocramius it's issue i.e. is reason to send PR with this test case. Closing unresolved issues does not solve the problems described in them.

**Comment by Ocramius** [comment] 2022-09-28 00:22
It's resolved according to @kukulich not being able to reproduce this.

Please consider opening a PR with a failing test case if you don't believe that to be true.
